version: '3.9'

services:
    app:
      build:
        context: .
      ports:
        - "8080:8080"
      volumes:
        - .:/src
      environment:
        DATABASE_URL: ${APP_CONFIG__DB__URL}
      depends_on:
        - db

    db:
      image: postgres:latest
      env_file:
        - .env
      environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
      ports:
        - "5432:5432"

    pgadmin:
      image: dpage/pgadmin4
      environment:
        PGADMIN_DEFAULT_EMAIL: va.baklanov@mail.ru
        PGADMIN_DEFAULT_PASSWORD: zxcqweasd
        PGADMIN_CONFIG_SERVER_MODE: 'False'
      ports:
        - "8081:80"
      depends_on:
        - db