"""Created User, Translation, UserProgress tables

Revision ID: c77e80817c63
Revises: 
Create Date: 2024-08-14 19:10:47.582507

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c77e80817c63"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "translation",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("english_word", sa.String(), nullable=False),
        sa.Column("russian_word", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_translation")),
    )
    op.create_index(
        op.f("ix_translation_english_word"),
        "translation",
        ["english_word"],
        unique=False,
    )
    op.create_index(
        op.f("ix_translation_id"), "translation", ["id"], unique=False
    )
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user")),
        sa.UniqueConstraint("username", name=op.f("uq_user_username")),
    )
    op.create_index(op.f("ix_user_id"), "user", ["id"], unique=False)
    op.create_table(
        "user_progress",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("translation_id", sa.Integer(), nullable=False),
        sa.Column("is_learned", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["translation_id"],
            ["translation.id"],
            name=op.f("fk_user_progress_translation_id_translation"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name=op.f("fk_user_progress_user_id_user"),
        ),
        sa.PrimaryKeyConstraint(
            "user_id", "translation_id", "id", name=op.f("pk_user_progress")
        ),
    )
    op.create_index(
        op.f("ix_user_progress_id"), "user_progress", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_progress_id"), table_name="user_progress")
    op.drop_table("user_progress")
    op.drop_index(op.f("ix_user_id"), table_name="user")
    op.drop_table("user")
    op.drop_index(op.f("ix_translation_id"), table_name="translation")
    op.drop_index(
        op.f("ix_translation_english_word"), table_name="translation"
    )
    op.drop_table("translation")
    # ### end Alembic commands ###
